// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "istio.io/client-go/pkg/apis/extensions/v1alpha1"
	extensionsv1alpha1 "istio.io/client-go/pkg/applyconfiguration/extensions/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrafficExtensions implements TrafficExtensionInterface
type FakeTrafficExtensions struct {
	Fake *FakeExtensionsV1alpha1
	ns   string
}

var trafficextensionsResource = v1alpha1.SchemeGroupVersion.WithResource("trafficextensions")

var trafficextensionsKind = v1alpha1.SchemeGroupVersion.WithKind("TrafficExtension")

// Get takes name of the trafficExtension, and returns the corresponding trafficExtension object, and an error if there is any.
func (c *FakeTrafficExtensions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TrafficExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trafficextensionsResource, c.ns, name), &v1alpha1.TrafficExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficExtension), err
}

// List takes label and field selectors, and returns the list of TrafficExtensions that match those selectors.
func (c *FakeTrafficExtensions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TrafficExtensionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trafficextensionsResource, trafficextensionsKind, c.ns, opts), &v1alpha1.TrafficExtensionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TrafficExtensionList{ListMeta: obj.(*v1alpha1.TrafficExtensionList).ListMeta}
	for _, item := range obj.(*v1alpha1.TrafficExtensionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trafficExtensions.
func (c *FakeTrafficExtensions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trafficextensionsResource, c.ns, opts))

}

// Create takes the representation of a trafficExtension and creates it.  Returns the server's representation of the trafficExtension, and an error, if there is any.
func (c *FakeTrafficExtensions) Create(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.CreateOptions) (result *v1alpha1.TrafficExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trafficextensionsResource, c.ns, trafficExtension), &v1alpha1.TrafficExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficExtension), err
}

// Update takes the representation of a trafficExtension and updates it. Returns the server's representation of the trafficExtension, and an error, if there is any.
func (c *FakeTrafficExtensions) Update(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.UpdateOptions) (result *v1alpha1.TrafficExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trafficextensionsResource, c.ns, trafficExtension), &v1alpha1.TrafficExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficExtension), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTrafficExtensions) UpdateStatus(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.UpdateOptions) (*v1alpha1.TrafficExtension, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(trafficextensionsResource, "status", c.ns, trafficExtension), &v1alpha1.TrafficExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficExtension), err
}

// Delete takes name of the trafficExtension and deletes it. Returns an error if one occurs.
func (c *FakeTrafficExtensions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(trafficextensionsResource, c.ns, name, opts), &v1alpha1.TrafficExtension{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrafficExtensions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trafficextensionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TrafficExtensionList{})
	return err
}

// Patch applies the patch and returns the patched trafficExtension.
func (c *FakeTrafficExtensions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrafficExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trafficextensionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TrafficExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficExtension), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied trafficExtension.
func (c *FakeTrafficExtensions) Apply(ctx context.Context, trafficExtension *extensionsv1alpha1.TrafficExtensionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficExtension, err error) {
	if trafficExtension == nil {
		return nil, fmt.Errorf("trafficExtension provided to Apply must not be nil")
	}
	data, err := json.Marshal(trafficExtension)
	if err != nil {
		return nil, err
	}
	name := trafficExtension.Name
	if name == nil {
		return nil, fmt.Errorf("trafficExtension.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trafficextensionsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.TrafficExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficExtension), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeTrafficExtensions) ApplyStatus(ctx context.Context, trafficExtension *extensionsv1alpha1.TrafficExtensionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficExtension, err error) {
	if trafficExtension == nil {
		return nil, fmt.Errorf("trafficExtension provided to Apply must not be nil")
	}
	data, err := json.Marshal(trafficExtension)
	if err != nil {
		return nil, err
	}
	name := trafficExtension.Name
	if name == nil {
		return nil, fmt.Errorf("trafficExtension.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trafficextensionsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.TrafficExtension{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficExtension), err
}
