// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "istio.io/client-go/pkg/apis/extensions/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TrafficExtensionLister helps list TrafficExtensions.
// All objects returned here must be treated as read-only.
type TrafficExtensionLister interface {
	// List lists all TrafficExtensions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TrafficExtension, err error)
	// TrafficExtensions returns an object that can list and get TrafficExtensions.
	TrafficExtensions(namespace string) TrafficExtensionNamespaceLister
	TrafficExtensionListerExpansion
}

// trafficExtensionLister implements the TrafficExtensionLister interface.
type trafficExtensionLister struct {
	indexer cache.Indexer
}

// NewTrafficExtensionLister returns a new TrafficExtensionLister.
func NewTrafficExtensionLister(indexer cache.Indexer) TrafficExtensionLister {
	return &trafficExtensionLister{indexer: indexer}
}

// List lists all TrafficExtensions in the indexer.
func (s *trafficExtensionLister) List(selector labels.Selector) (ret []*v1alpha1.TrafficExtension, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TrafficExtension))
	})
	return ret, err
}

// TrafficExtensions returns an object that can list and get TrafficExtensions.
func (s *trafficExtensionLister) TrafficExtensions(namespace string) TrafficExtensionNamespaceLister {
	return trafficExtensionNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// TrafficExtensionNamespaceLister helps list and get TrafficExtensions.
// All objects returned here must be treated as read-only.
type TrafficExtensionNamespaceLister interface {
	// List lists all TrafficExtensions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TrafficExtension, err error)
	// Get retrieves the TrafficExtension from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.TrafficExtension, error)
	TrafficExtensionNamespaceListerExpansion
}

// trafficExtensionNamespaceLister implements the TrafficExtensionNamespaceLister
// interface.
type trafficExtensionNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all TrafficExtensions in the indexer for a given namespace.
func (s trafficExtensionNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.TrafficExtension, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TrafficExtension))
	})
	return ret, err
}

// Get retrieves the TrafficExtension from the indexer for a given namespace and name.
func (s trafficExtensionNamespaceLister) Get(name string) (*v1alpha1.TrafficExtension, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("trafficextension"), name)
	}
	return obj.(*v1alpha1.TrafficExtension), nil
}
