// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "istio.io/client-go/pkg/apis/extensions/v1alpha1"
	extensionsv1alpha1 "istio.io/client-go/pkg/applyconfiguration/extensions/v1alpha1"
	scheme "istio.io/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TrafficExtensionsGetter has a method to return a TrafficExtensionInterface.
// A group's client should implement this interface.
type TrafficExtensionsGetter interface {
	TrafficExtensions(namespace string) TrafficExtensionInterface
}

// TrafficExtensionInterface has methods to work with TrafficExtension resources.
type TrafficExtensionInterface interface {
	Create(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.CreateOptions) (*v1alpha1.TrafficExtension, error)
	Update(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.UpdateOptions) (*v1alpha1.TrafficExtension, error)
	UpdateStatus(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.UpdateOptions) (*v1alpha1.TrafficExtension, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TrafficExtension, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TrafficExtensionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrafficExtension, err error)
	Apply(ctx context.Context, trafficExtension *extensionsv1alpha1.TrafficExtensionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficExtension, err error)
	ApplyStatus(ctx context.Context, trafficExtension *extensionsv1alpha1.TrafficExtensionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficExtension, err error)
	TrafficExtensionExpansion
}

// trafficExtensions implements TrafficExtensionInterface
type trafficExtensions struct {
	client rest.Interface
	ns     string
}

// newTrafficExtensions returns a TrafficExtensions
func newTrafficExtensions(c *ExtensionsV1alpha1Client, namespace string) *trafficExtensions {
	return &trafficExtensions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the trafficExtension, and returns the corresponding trafficExtension object, and an error if there is any.
func (c *trafficExtensions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TrafficExtension, err error) {
	result = &v1alpha1.TrafficExtension{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trafficextensions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TrafficExtensions that match those selectors.
func (c *trafficExtensions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TrafficExtensionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TrafficExtensionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trafficextensions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested trafficExtensions.
func (c *trafficExtensions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("trafficextensions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a trafficExtension and creates it.  Returns the server's representation of the trafficExtension, and an error, if there is any.
func (c *trafficExtensions) Create(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.CreateOptions) (result *v1alpha1.TrafficExtension, err error) {
	result = &v1alpha1.TrafficExtension{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("trafficextensions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficExtension).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a trafficExtension and updates it. Returns the server's representation of the trafficExtension, and an error, if there is any.
func (c *trafficExtensions) Update(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.UpdateOptions) (result *v1alpha1.TrafficExtension, err error) {
	result = &v1alpha1.TrafficExtension{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trafficextensions").
		Name(trafficExtension.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficExtension).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *trafficExtensions) UpdateStatus(ctx context.Context, trafficExtension *v1alpha1.TrafficExtension, opts v1.UpdateOptions) (result *v1alpha1.TrafficExtension, err error) {
	result = &v1alpha1.TrafficExtension{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trafficextensions").
		Name(trafficExtension.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficExtension).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the trafficExtension and deletes it. Returns an error if one occurs.
func (c *trafficExtensions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trafficextensions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *trafficExtensions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trafficextensions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched trafficExtension.
func (c *trafficExtensions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrafficExtension, err error) {
	result = &v1alpha1.TrafficExtension{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("trafficextensions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied trafficExtension.
func (c *trafficExtensions) Apply(ctx context.Context, trafficExtension *extensionsv1alpha1.TrafficExtensionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficExtension, err error) {
	if trafficExtension == nil {
		return nil, fmt.Errorf("trafficExtension provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(trafficExtension)
	if err != nil {
		return nil, err
	}
	name := trafficExtension.Name
	if name == nil {
		return nil, fmt.Errorf("trafficExtension.Name must be provided to Apply")
	}
	result = &v1alpha1.TrafficExtension{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("trafficextensions").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *trafficExtensions) ApplyStatus(ctx context.Context, trafficExtension *extensionsv1alpha1.TrafficExtensionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficExtension, err error) {
	if trafficExtension == nil {
		return nil, fmt.Errorf("trafficExtension provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(trafficExtension)
	if err != nil {
		return nil, err
	}

	name := trafficExtension.Name
	if name == nil {
		return nil, fmt.Errorf("trafficExtension.Name must be provided to Apply")
	}

	result = &v1alpha1.TrafficExtension{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("trafficextensions").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
