// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "istio.io/client-go/pkg/apis/security/v1beta1"
	scheme "istio.io/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PeerAuthenticationsGetter has a method to return a PeerAuthenticationInterface.
// A group's client should implement this interface.
type PeerAuthenticationsGetter interface {
	PeerAuthentications(namespace string) PeerAuthenticationInterface
}

// PeerAuthenticationInterface has methods to work with PeerAuthentication resources.
type PeerAuthenticationInterface interface {
	Create(*v1beta1.PeerAuthentication) (*v1beta1.PeerAuthentication, error)
	Update(*v1beta1.PeerAuthentication) (*v1beta1.PeerAuthentication, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.PeerAuthentication, error)
	List(opts v1.ListOptions) (*v1beta1.PeerAuthenticationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.PeerAuthentication, err error)
	PeerAuthenticationExpansion
}

// peerAuthentications implements PeerAuthenticationInterface
type peerAuthentications struct {
	client rest.Interface
	ns     string
}

// newPeerAuthentications returns a PeerAuthentications
func newPeerAuthentications(c *SecurityV1beta1Client, namespace string) *peerAuthentications {
	return &peerAuthentications{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the peerAuthentication, and returns the corresponding peerAuthentication object, and an error if there is any.
func (c *peerAuthentications) Get(name string, options v1.GetOptions) (result *v1beta1.PeerAuthentication, err error) {
	result = &v1beta1.PeerAuthentication{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("peerauthentications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PeerAuthentications that match those selectors.
func (c *peerAuthentications) List(opts v1.ListOptions) (result *v1beta1.PeerAuthenticationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.PeerAuthenticationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("peerauthentications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested peerAuthentications.
func (c *peerAuthentications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("peerauthentications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a peerAuthentication and creates it.  Returns the server's representation of the peerAuthentication, and an error, if there is any.
func (c *peerAuthentications) Create(peerAuthentication *v1beta1.PeerAuthentication) (result *v1beta1.PeerAuthentication, err error) {
	result = &v1beta1.PeerAuthentication{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("peerauthentications").
		Body(peerAuthentication).
		Do().
		Into(result)
	return
}

// Update takes the representation of a peerAuthentication and updates it. Returns the server's representation of the peerAuthentication, and an error, if there is any.
func (c *peerAuthentications) Update(peerAuthentication *v1beta1.PeerAuthentication) (result *v1beta1.PeerAuthentication, err error) {
	result = &v1beta1.PeerAuthentication{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("peerauthentications").
		Name(peerAuthentication.Name).
		Body(peerAuthentication).
		Do().
		Into(result)
	return
}

// Delete takes name of the peerAuthentication and deletes it. Returns an error if one occurs.
func (c *peerAuthentications) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("peerauthentications").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *peerAuthentications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("peerauthentications").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched peerAuthentication.
func (c *peerAuthentications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.PeerAuthentication, err error) {
	result = &v1beta1.PeerAuthentication{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("peerauthentications").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
