// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "istio.io/client-go/pkg/apis/security/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePeerAuthentications implements PeerAuthenticationInterface
type FakePeerAuthentications struct {
	Fake *FakeSecurityV1beta1
	ns   string
}

var peerauthenticationsResource = schema.GroupVersionResource{Group: "security.istio.io", Version: "v1beta1", Resource: "peerauthentications"}

var peerauthenticationsKind = schema.GroupVersionKind{Group: "security.istio.io", Version: "v1beta1", Kind: "PeerAuthentication"}

// Get takes name of the peerAuthentication, and returns the corresponding peerAuthentication object, and an error if there is any.
func (c *FakePeerAuthentications) Get(name string, options v1.GetOptions) (result *v1beta1.PeerAuthentication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(peerauthenticationsResource, c.ns, name), &v1beta1.PeerAuthentication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PeerAuthentication), err
}

// List takes label and field selectors, and returns the list of PeerAuthentications that match those selectors.
func (c *FakePeerAuthentications) List(opts v1.ListOptions) (result *v1beta1.PeerAuthenticationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(peerauthenticationsResource, peerauthenticationsKind, c.ns, opts), &v1beta1.PeerAuthenticationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.PeerAuthenticationList{ListMeta: obj.(*v1beta1.PeerAuthenticationList).ListMeta}
	for _, item := range obj.(*v1beta1.PeerAuthenticationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested peerAuthentications.
func (c *FakePeerAuthentications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(peerauthenticationsResource, c.ns, opts))

}

// Create takes the representation of a peerAuthentication and creates it.  Returns the server's representation of the peerAuthentication, and an error, if there is any.
func (c *FakePeerAuthentications) Create(peerAuthentication *v1beta1.PeerAuthentication) (result *v1beta1.PeerAuthentication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(peerauthenticationsResource, c.ns, peerAuthentication), &v1beta1.PeerAuthentication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PeerAuthentication), err
}

// Update takes the representation of a peerAuthentication and updates it. Returns the server's representation of the peerAuthentication, and an error, if there is any.
func (c *FakePeerAuthentications) Update(peerAuthentication *v1beta1.PeerAuthentication) (result *v1beta1.PeerAuthentication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(peerauthenticationsResource, c.ns, peerAuthentication), &v1beta1.PeerAuthentication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PeerAuthentication), err
}

// Delete takes name of the peerAuthentication and deletes it. Returns an error if one occurs.
func (c *FakePeerAuthentications) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(peerauthenticationsResource, c.ns, name), &v1beta1.PeerAuthentication{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePeerAuthentications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(peerauthenticationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.PeerAuthenticationList{})
	return err
}

// Patch applies the patch and returns the patched peerAuthentication.
func (c *FakePeerAuthentications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.PeerAuthentication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(peerauthenticationsResource, c.ns, name, pt, data, subresources...), &v1beta1.PeerAuthentication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PeerAuthentication), err
}
